spring:
  application:
    name: Circuit_Breaker

management:
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
        

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
